version: "3"
services:
  menusaz.identity:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
      - "8001:443"
    restart: always
    environment:
      SPNETCORE_ENVIRONMENT: ${PROFILE}
      CUSTOMCONNSTR_Default: ${CONNECTION_STRING}